services:
  mongo:
    image: mongo:7
    container_name: mission5-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  server:
    build: ./server
    container_name: mission5-server
    ports:
      - "3000:3000"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  client:
    build: ./client
    container_name: mission5-client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server

volumes:
  mongo_data:
